[package]
name = "vidyut-prakriya"
version = "0.1.0"
authors = ["Arun Prasad <ambuda.library@gmail.com>"]
description = "A Sanskrit word generator"
homepage = "https://github.com/ambuda-org/vidyut"
repository = "https://github.com/ambuda-org/vidyut"
categories = ["text-processing"]
keywords = ["sanskrit"]
license = "MIT"
edition = "2021"

[dependencies]
clap = { version = "4.0.12", features = ["derive"] }
compact_str = { version = "0.6.1", features = ["serde"] }
csv = "1.1.6"
enumset = { version = "1.0.12", features = ["serde"] }
lazy_static = "1.4.0"
serde = { version = "1.0.150", features = ["derive"] }
sha2 = "0.10.6"
sha256 = "1.1.1"
wasm-bindgen = "0.2"
serde-wasm-bindgen = "0.4"
console_error_panic_hook = "0.1.7"

[dev-dependencies]
test_utils = { path = "test_utils" }

[lib]
crate-type = ["cdylib", "rlib"]
